### PR TITLE
Added endpoint for finding a specific launchpad

### PR DESCRIPTION
**Pull request by waterskier2007**
I am really not sure if this will work because I have no visibility into the Mongo database structure. Please review and comment if you’d like more info as to the intent

### CODE REVIEW

**Comment by jhpratt** [comment]
Looks good to me. I've just added Jake as a reviewer, as I don't have a local DB copy to test on.

**Comment by waterskier2007** [comment]
@jhpratt the only part I am leery about is the fact that the code seems to indicate that client[:launchpad] returns a collection however the launchpads endpoint returns a json dictionary. Therefore, I am not sure how the collection.find will behave

**Comment by jhpratt** [comment]
Not sure, I haven't dug through the code too much ─ I just have a general idea of how it works (I reworked a couple endpoints). That's why I've tagged Jake and let him know on Slack.

**Comment by jakewmeyer** [comment]
@waterskier2007 Are just trying to get the individual launchpad data? Or are you trying to sort the launches by launch id?

**Comment by waterskier2007** [comment]
Just pull an individual launchpad by id

**Comment by jakewmeyer** [comment]
@waterskier2007 Looking for the correct mongo syntax, the query is the problem at the moment

**Comment by waterskier2007** [comment]
Ok. I figured it might not be perfect. I just based it on another id lookup

**Comment by jakewmeyer** [comment]
So there's two potential solutions here.

Option 1: Change the schema of launchpads to allow for queries. Queries in MongoDB can only return a whole "document", and the whole page is currently a single document. I could separate each launchpad into unique documents, like the launches, cores, caps, etc...

Option 2: You could also parse the information out on the front end, but It probably makes more sense to split them into unique documents, it would also make the querying easier in the future.

**Comment by jakewmeyer** [comment]
@jhpratt @waterskier2007 Additionally, there are read only credentials in app.rb for access to the database if you want to see the structure, and I include the latest mongo dump on the [release](https://github.com/r-spacex/SpaceX-API/releases) page.

Also, I switched on a feature in Heroku that spins up a new instance for every new pull request, to allow for testing and checking features before merging. The "view deployment" message from earlier takes you to the url. As more changes are made to the PR, they get automatically pushed to the instance.

**Comment by jakewmeyer** [comment]
I changed the schema for launchpads, and this should work now, I'll go ahead and merge

**Pull request merged**
