### PR TITLE
tweak to launchpads syntax

### PR DESCRIPTION
**Pull request by waterskier2007**

### CODE REVIEW

**Comment by waterskier2007** [comment]
Feel free to comment on these changes or do what you want with them, but I think it's better to return an array of items instead of an array of dictionaries where the keys are simply IDs for the items in the arrays

**Comment by jakewmeyer** [comment]
It's funny because I had it that way a few days ago, but switched it to how it is now.

If it makes it easier to work with, I'm all for it. You're right, it's a bit redundant when ID's are added.

**Comment by waterskier2007** [comment]
Hey @jakewmeyer, has this been deployed? I am still seeing the old structure at https://api.spacexdata.com/launchpads

**Comment by jakewmeyer** [comment]
Sorry, it should be there now 👍

**Comment by waterskier2007** [comment]
sweet!

**Pull request merged**
