### PR TITLE
fixed issue #36

### PR DESCRIPTION
**Pull request by waterskier2007**

### CODE REVIEW

**Comment by waterskier2007** [comment]
@jakewmeyer odd, it looks like cores are fixed but caps are not. Can you confirm?

**Comment by jakewmeyer** [comment]
Looks like you added it to the wrong endpoint, should've been on the one where it searches individual caps, not filtering the launches by caps.

Should be fixed now 👍

**Comment by waterskier2007** [comment]
Oh wow, sorry about that man.

**Comment by jakewmeyer** [comment]
No worries, I should've looked at it a bit closer before merging.

**Pull request merged**
