### PR TITLE
updates for issue #8

### PR DESCRIPTION
**Pull request by waterskier2007**
Just some tweaks that I think make sense. Feel free to ignore it if you don’t agree :)

### CODE REVIEW

**Comment by jakewmeyer** [comment]
Sounds good, I wasn't 100% sure what the convention was, I structured it this way originally, but changed at some point. If it's the standard, we'll go with that. 👍

**Comment by waterskier2007** [comment]
Yeah, there may be some other endpoints that it's applicable to as well.

**Comment by jakewmeyer** [comment]
Sorting by year and date range might be similar

**Comment by waterskier2007** [comment]
Yes, for those endpoints you might want to use query string parameters instead of having the parameters right in the url like that. I've never seen it done that way, and I'd throw in a merge request, but i am not that familiar with ruby. Basically, instead of 

https://api.spacexdata.com/launches/from=2011-01-20/to=2017-05-25

You'd want something like this

https://api.spacexdata.com/launches/?from=2011-01-20&to=2017-05-25

**Comment by jakewmeyer** [comment]
Updated, looks to be better in line with the standards, with the query params clearly separated out from the rest of the url.

[https://api.spacexdata.com/launches?from=2011-01-20&to=2017-05-25](https://api.spacexdata.com/launches?from=2011-01-20&to=2017-05-25)

**Comment by waterskier2007** [comment]
Dude, awesome. I know you're probably sick of my input, but one last thing that I would change... I am going to throw in another issue and pull request

**Comment by jakewmeyer** [comment]
Not sick at all, all solid changes. Feedback is good. 👍

**Pull request merged**
