### PR TITLE
Added Launch Library support

### PR DESCRIPTION
**Pull request by mathisbeauty**
Implemented threshold to fetch launch dates from [Launch Library API](https://launchlibrary.net/docs/1.4/api.html).

I attach a txt to compare both APIs rapidly.
[example_queries.txt](https://github.com/r-spacex/SpaceX-API/files/3526792/example_queries.txt)

### CODE REVIEW

**Comment by jakewmeyer** [comment]
Just one thing to maybe consider:

1. This assumes that the mission name will be exactly the same as what they have in LL, which might not always be the case. We might want to fuzzy match to something reasonably close.

**Comment by mathisbeauty** [comment]
I have implemented the fuzzy match and also reduced the number of requests to the LL API to 1, instead of one per launch to update.

Let me know what you think.

**Comment by mathisbeauty** [comment]
Also, it may be a good idea to hide the new fields 'last_wiki_update' and 'is_date_from_wiki' from the API responses.

**Comment by jakewmeyer** [comment]
Might be useful to some? I'd rather keep them in the response.

Everything looks good, I'll merge this shortly.

Overall awesome work, with lots of good comments, appreciate you knocking this out for us 👍

**Comment by mathisbeauty** [comment]
Thank you! Glad to help 👍
Also, I have tons of free time, so I'm thinking of contributing with another feature, like:
- [Twitter scraping for live updates](https://github.com/r-spacex/SpaceX-API/issues/1#issuecomment-488992564)
- Making the backup APIs a list instead of just Launch Library. Having different "Providers" from which to gather the data. E.g. Twitter, other APIs, etc.
- Writing tests for the "scripts" folder
- Etc

Let me know which one as a higher priority, or another feature that you need help with, and I'll be glad to create an issue and start working on it.

Cheers!

**Pull request merged**
